### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by CodeIgniter**
Fix small resolution, the footer on the right background overlap.

### CODE REVIEW

**Comment by CodeIgniter** [comment]
and Fix small resolution button(a element) text display problems.

**Comment by jim-parry** [comment]
I see what you are trying to do with the ".footer .nav" rule. Wouldn't a better solution be to hide the bcit50 logo if using a small device? Not sure if this would involve the "xs" qualifier in bootstrap, or if it would be done using a media query.

**Comment by jim-parry** [comment]
I am not sure of the reason for your second change, to .btn.btn-block. 
The only change I see with it in place is that the github button text on the homepage gets unbolded.
What is the "text display problem" you allude to?

**Comment by jim-parry** [comment]
ps - if the changes address different issues, it would be better to use separate pull requests, so they can be considered independently.

**Comment by CodeIgniter** [comment]
Thank you for your reply.

1. About small device, I think change this rule is the easiest solution, after the test has not been found to have side effects. Of course, this is not the perfect solution. Do you have other ideas? :)

2. using a small device, some buttons text will be cut off, you can try. For example: http://www.codeigniter.com/docs

example

**Comment by jim-parry** [comment]
Re the footer, instead of adding a footer margin, just changing the bcit50 rule to be 
.bcit50 .hidden-xs {
    background: url('/assets/images/bcit-50.png') right top no-repeat;
    background-size: 100px 44px;
}
leaves the footer text menu intact (no additional line), by hiding the background bcit50 image at "extra small" resolutions.

**Comment by jim-parry** [comment]
When I tested your btn btn-block change, the text on the docs buttons might be a bit better, but it is still cut off :( I am going to play with the button text instead, so we don't need this part of your PR.

**Comment by CodeIgniter** [comment]
About button text, I modified the effect is:
example2
I think the word wrap should be a good choice, can be adapted to almost any situation, and modify the text length is not a good choice. :)

**Comment by jim-parry** [comment]
Word wrap could be more elegant than really shortened text, agreed. 
You'll have to push the changes you suggest to your develop branch for them to show up here.
I plan to shorten some of the button text in any case, eliminating version specifics.

ps - PRs are most easily handled as a feature branch in your repo. Using just "develop" means that all of the changes you might be working on get lumped together. If they are isolated in their own branch, they can be considered independtly, and you can resync repos (bcit-ci/develop with your/develop) and eliminate your branch if/when one is adopted.

**Comment by CodeIgniter** [comment]
OK. :)

**Pull request closed without merging**
