### PR TITLE
clean up: convert spaces to tabs

### PR DESCRIPTION
**Pull request by zhanghongyi**
I noticed there are some clean ups ongoing. Some files still have mixed indentations. I am trying to help the clean-ups by converting spaces to tabs. Are tabs preferred?

### CODE REVIEW

**Comment by jim-parry** [comment]
The general rule is tabs for indent, spaces for alignment within/under an indent.
Thanks!

**Comment by jim-parry** [comment]
Good catch, thank you. I suspect I had my editor settings incorrect back when those were created :-/

fyi - Andrey will not accept PRs for the main repo that are just formatting. If formatting accompanies another PR, that is fine. He tries really hard not to let any inconsistencies through!

**Comment by zhanghongyi** [comment]
@jim-parry Thanks for the tip :)

**Comment by CodeIgniter** [comment]
@jim-parry I think use the space better than using tab, because different editor tab width is different.

**Comment by jim-parry** [comment]
@CodeIgniter Our convention inside the CI project is to use tabs for indentation. Yes, different editors or individual's preferences may differ, but that is a matter of personal preference.

**Pull request merged**
