### PR TITLE
Replace external Github stats with Github API

### PR DESCRIPTION
**Pull request by xkb**
I'm anticipating a discussion on the design changes I made here, everyone is welcome to share their thoughts. I'm no UI expert.

Will squash all the commits when this is good-to-go.

### CODE REVIEW

**Comment by jim-parry** [comment]
@michalsn What do you think? Does this adversely impact the design you came up with?

**Comment by michalsn** [comment]
@jim-parry CSS needs some updates but it can be done after you accept this pull request. 
I will prepare something later today.

**Comment by jim-parry** [comment]
I think you have your IDE settings wrong ... you have replaced leading tabs with spaces :(

**Comment by jim-parry** [comment]
I see there is PHP in jumbotitle.php ... that can be refactored out later, using a view fragment.

**Comment by jim-parry** [comment]
@michalsn I will let you play with the styling before I go messing with formatting :)

**Pull request merged**
