### PR TITLE
change button to primary in community page

### PR DESCRIPTION
**Pull request by zhanghongyi**
I wonder if there is some special reason that the button types are inconsistent in community page. Visit Forum button is orange and Github and IRC buttons are grey. If this is not due the special design, I would propose to change the default type to primary so that the colors would be consistent. A grey button look like disabled to me...

### CODE REVIEW

**Comment by jim-parry** [comment]
The IRC & Github links are to external sites, and I wanted the links to look different than links to "our" site(s). Grey may not be the best choice, but I think they should be distinct from internal links.

**Comment by zhanghongyi** [comment]
That makes sense now. Do you think there is a need to change grey to other colors like yellow? Otherwise, I can live with the grey since the distinction is specifically designed. As for the color choice, it's just personal preference.

**Comment by jim-parry** [comment]
It would probably make sense to have the colors meaningful...
- btn-primary for CI3 on the download & documentation pages,
- btn-warning or btn-danger for the CI2 links on those pages,
- btn-primary or btn-success for the forum link on the community page,
- btn-info for the IRC & github links on the community page

What do you think?

btw, some of the download links are to github releases, so my earlier comment about distinguishing "our" from "theirs" might be a bit mis-guided.

**Comment by zhanghongyi** [comment]
Most of the button types already make much sense. :+1: I just tried to change the button type to info and the color of info type is light blue. Having button type of info is a good choice, but I am not sure if the color light blue would looks good on our website. 

Btw, now I kinda understand why the default is grey as the bootstrap default is white. It is because the second major color of the website is grey indeed. I am just confused from a user's perspective at first, now I see the meanings behind it. 

Whether to change it to blue is up to you. Making them have type info is better than default, but I am not sure if light blue would be better than grey. I would not mind closing the pull request. :)

**Comment by jim-parry** [comment]
I will go along with these if you want to make the changes :)

-    btn-primary for CI3 on the download & documentation pages,
-    btn-warning for the CI2 links on those pages,
-    btn-primary for the forum link on the community page,
-    btn-info for the IRC & github links on the community page

**Comment by zhanghongyi** [comment]
For sure, will do it.

**Comment by zhanghongyi** [comment]
@jim-parry not sure if you noticed my new commit. Any opinions?

**Comment by jim-parry** [comment]
I saw your commit. I thought you were going to change the others too, but I can do that :)

**Comment by zhanghongyi** [comment]
I thought these are all the changes that to make. Anywhere else that is inconsistent with the design?

**Comment by jim-parry** [comment]
ci2 vs ci3 on the downlaods page, i think ... all done :)

**Comment by zhanghongyi** [comment]
ah, did not notice that before :)

**Pull request merged**
